#!/bin/sh

set -e

cwd=$(dirname "$0")
host=$1

size=$(cat "$cwd"/../rundata/size)
iterations=$(cat "$cwd"/../rundata/iterations)

printf "iterations=$iterations\nsize=$size\n$(cat "$cwd"/script.py)" \
    | ssh "$host.local" python > "$cwd/../rundata/results/$host.out"
