#!/bin/sh

set -e

cwd=$(dirname "$0")
host=$1

size=$(cat "$cwd"/../rundata/size)
iterations=$(cat "$cwd"/../rundata/iterations)
resultfile="$cwd"/../rundata/results/"$host".out
fakeargs="iterations=$iterations\nsize=$size"
scriptfile="$cwd"/script.py

rm -f "$resultfile"

printf "$fakeargs\n$(cat $scriptfile)" \
    | ssh "$host.local" python > "$resultfile"
